name: JSON Toolkit

on:
  schedule:
    # Once per day, Monday to Friday
    - cron: '0 19 * * 1-5'
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: macos-latest
            compiler: llvm
            type: static
          - os: macos-latest
            compiler: llvm
            type: shared
          - os: ubuntu-latest
            compiler: llvm
            type: static
          - os: ubuntu-latest
            compiler: gcc
            type: static
          - os: ubuntu-latest
            compiler: llvm
            type: shared
          - os: ubuntu-latest
            compiler: gcc
            type: shared
          - os: windows-latest
            compiler: msvc
            type: static
          - os: windows-latest
            compiler: msvc
            type: shared

          # Sanitizers
          - os: ubuntu-latest
            compiler: llvm
            type: static
            options: -DJSONTOOLKIT_ADDRESS_SANITIZER:BOOL=ON
          - os: ubuntu-latest
            compiler: llvm
            type: static
            options: -DJSONTOOLKIT_UNDEFINED_SANITIZER:BOOL=ON

    runs-on: ${{ matrix.platform.os }}
    steps:
      - uses: actions/checkout@v4

      - name: Installing dependencies
        uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: dependencies
      - name: Configuring
        uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: configure
          mode: ${{ matrix.platform.type }}
          compiler: ${{ matrix.platform.compiler }}
          options: -DJSONTOOLKIT_TESTS:BOOL=ON -DJSONTOOLKIT_DOCS:BOOL=OFF ${{ matrix.platform.options }}
      - name: Check
        uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: check
      - name: Build
        uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: build
      - name: Install
        uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: install
          component: jsontoolkit
      - name: Test
        uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: test

  unikraft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: unikraft
