name: JSON Toolkit

on:
  schedule:
    # Once per day, Monday to Friday
    - cron: '0 19 * * 1-5'
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: windows-latest
            type: static
            shell: pwsh

    defaults:
      run:
        shell: ${{ matrix.platform.shell }}

    runs-on: ${{ matrix.platform.os }}
    env:
      CC: ${{ matrix.platform.cc }}
      CXX: ${{ matrix.platform.cxx }}
    steps:
      - uses: actions/checkout@v3
      - run: cmake --version
      - name: Configure JSON Toolkit (static)
        if: matrix.platform.type == 'static'
        run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DJSONTOOLKIT_JSONL:BOOL=OFF
          -DJSONTOOLKIT_JSONSCHEMA:BOOL=OFF
          -DJSONTOOLKIT_JSONPOINTER:BOOL=OFF
          -DJSONTOOLKIT_URI:BOOL=OFF
          -DJSONTOOLKIT_TESTS:BOOL=ON
          -DJSONTOOLKIT_DOCS:BOOL=OFF
          -DBUILD_SHARED_LIBS:BOOL=OFF
          -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
          ${{ matrix.platform.options }}
      - run: cmake --build ./build --config Release --parallel 4

      - run: dir build

      - run: cd ./build && ctest --build-config Release --output-on-failure --parallel --verbose
