name: Example

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    defaults:
      run:
        shell: pwsh

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Configure
        run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
      - run: cmake --build ./build --config Release --parallel 4
      - run: cd ./build && ctest --build-config Release --verbose
      - run: cd ./build && ctest --build-config Release --verbose
      - run: cd ./build && ctest --build-config Release --verbose
      - run: cd ./build && ctest --build-config Release --verbose
