name: JSON Toolkit

on:
  - push

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: macos-11
            cc: clang
            cxx: clang++
            type: static
          - os: macos-11
            cc: clang
            cxx: clang++
            type: shared
          - os: ubuntu-22.04
            cc: clang
            cxx: clang++
            type: static
          - os: ubuntu-22.04
            cc: gcc
            cxx: g++
            type: static
          - os: ubuntu-22.04
            cc: clang
            cxx: clang++
            type: shared
          - os: ubuntu-22.04
            cc: gcc
            cxx: g++
            type: shared
          - os: windows-2022
            type: static
          # TODO: Make shared libraries work on Windows
          # - os: windows-2022
            # type: shared

          # Sanitizers
          - os: ubuntu-22.04
            cc: clang
            cxx: clang++
            type: static
            options: -DJSONTOOLKIT_ADDRESS_SANITIZER:BOOL=ON

    runs-on: ${{ matrix.platform.os }}
    env:
      CC: ${{ matrix.platform.cc }}
      CXX: ${{ matrix.platform.cxx }}
    steps:
      - name: Install dependencies (GNU/Linux)
        if: runner.os == 'linux'
        run: sudo apt-get install --yes googletest clang-format
      - uses: actions/checkout@v3
      - name: Install dependencies (macOS)
        if: runner.os == 'macos'
        run: brew bundle
        env:
          HOMEBREW_NO_ANALYTICS: 1
          HOMEBREW_NO_AUTO_UPDATE: 1
      - run: cmake --version
      - name: Configure JSON Toolkit (static)
        if: matrix.platform.type == 'static'
        run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DJSONTOOLKIT_CONTRIB:BOOL=ON
          -DJSONTOOLKIT_TESTS:BOOL=ON
          -DJSONTOOLKIT_DOCS:BOOL=OFF
          -DBUILD_SHARED_LIBS:BOOL=OFF
          -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
          ${{ matrix.platform.options }}
      - name: Configure JSON Toolkit (shared)
        if: matrix.platform.type == 'shared'
        run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DJSONTOOLKIT_CONTRIB:BOOL=ON
          -DJSONTOOLKIT_TESTS:BOOL=ON
          -DJSONTOOLKIT_DOCS:BOOL=OFF
          -DBUILD_SHARED_LIBS:BOOL=ON
          -DCMAKE_COMPILE_WARNING_AS_ERROR:BOOL=ON
          ${{ matrix.platform.options }}
      - run: cmake --build ./build --config Release --target clang_format_test
      - run: cmake --build ./build --config Release --parallel
      # Not every CTest version supports the --test-dir option. If such option
      # is not recognized, `ctest` will successfully exit finding no tests.
      # Better to be sure and `cd` all the time here.
      - run: >
          cmake --install ./build --prefix ./build/dist --config Release --verbose
          --component sourcemeta_jsontoolkit
      - run: >
          cmake --install ./build --prefix ./build/dist --config Release --verbose
          --component sourcemeta_jsontoolkit_dev
      - run: cd ./build && ctest --build-config Release --output-on-failure --parallel
