name: website
on:
  pull_request:

concurrency:
  group: website-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y doxygen
      - run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DSOURCEMETA_CORE_LANG_IO:BOOL=OFF
          -DSOURCEMETA_CORE_TIME:BOOL=OFF
          -DSOURCEMETA_CORE_UUID:BOOL=OFF
          -DSOURCEMETA_CORE_GZIP:BOOL=OFF
          -DSOURCEMETA_CORE_REGEX:BOOL=OFF
          -DSOURCEMETA_CORE_URI:BOOL=OFF
          -DSOURCEMETA_CORE_JSON:BOOL=OFF
          -DSOURCEMETA_CORE_JSONL:BOOL=OFF
          -DSOURCEMETA_CORE_JSONSCHEMA:BOOL=OFF
          -DSOURCEMETA_CORE_JSONPOINTER:BOOL=OFF
          -DSOURCEMETA_CORE_YAML:BOOL=OFF
          -DSOURCEMETA_CORE_EXTENSION_ALTERSCHEMA:BOOL=OFF
          -DSOURCEMETA_CORE_EXTENSION_EDITORSCHEMA:BOOL=OFF
          -DSOURCEMETA_CORE_EXTENSION_OPTIONS:BOOL=OFF
          -DSOURCEMETA_CORE_EXTENSION_BUILD:BOOL=OFF
          -DSOURCEMETA_CORE_DOCS:BOOL=ON
      - run: cmake --build ./build --config Release --target doxygen
