name: website
on:
  pull_request:

concurrency:
  group: website-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - run: sudo apt update
      - run: sudo apt install -y doxygen
      - run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DJSONTOOLKIT_URI:BOOL=OFF
          -DJSONTOOLKIT_JSON:BOOL=OFF
          -DJSONTOOLKIT_JSONSCHEMA:BOOL=OFF
          -DJSONTOOLKIT_JSONPOINTER:BOOL=OFF
          -DJSONTOOLKIT_CONTRIB:BOOL=OFF
          -DJSONTOOLKIT_TESTS:BOOL=OFF
          -DJSONTOOLKIT_DOCS:BOOL=ON
      - run: cmake --build ./build --config Release --target doxygen
