name: website
on:
  pull_request:

concurrency:
  group: website-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: sudo apt update
      - run: sudo apt install -y doxygen
      - run: >
          cmake -S . -B ./build
          -DCMAKE_BUILD_TYPE:STRING=Release
          -DJSONTOOLKIT_CORE_URI:BOOL=OFF
          -DJSONTOOLKIT_CORE_JSON:BOOL=OFF
          -DJSONTOOLKIT_CORE_JSONSCHEMA:BOOL=OFF
          -DJSONTOOLKIT_CORE_JSONPOINTER:BOOL=OFF
          -DJSONTOOLKIT_CORE_YAML:BOOL=OFF
          -DJSONTOOLKIT_DOCS:BOOL=ON
      - run: cmake --build ./build --config Release --target doxygen
