name: website
on:
  pull_request:

concurrency:
  group: website-build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing dependencies
        uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: dependencies
      - name: Configuring
        uses: sourcemeta/noa@2453614b746c2ca6f25b5044f71688efee22fb51
        with:
          step: configure
          compiler: auto
          mode: static
          options: -DJSONTOOLKIT_DOCS_ONLY:BOOL=ON
      - name: Doxygen
        uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: doxygen
