name: website
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: website-deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Installing dependencies
        uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: dependencies
      - name: Configuring
        uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: configure
          compiler: auto
          mode: static
          options: -DJSONTOOLKIT_DOCS_ONLY:BOOL=ON
      - name: Doxygen
        uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: doxygen
      - name: Website
        uses: sourcemeta/noa@035f7a9270e7bac134455b04e7acb649b68bdd1e
        with:
          step: website
